validation: sovereign
version: 1
accounts:
    - name: alice
      coins:
        - 20000token
        - 200000000stake
    - name: bob
      coins:
        - 10000token
        - 100000000stake
    - name: batman
      coins:
        - 10000token
        - 100000000stake
      mnemonic: private scheme nerve gallery satoshi flavor grow dial embrace plug taste diary
faucet:
    name: bob
    coins:
        - 5token
        - 100000stake
client:
    typescript:
        path: ts-client
    composables:
        path: vue/src/composables
    openapi:
        path: docs/static/openapi.json
default_denom: stake
validators:
    - name: alice
      bonded: 100000000stake
    - name: validator1
      bonded: 200000000stake
    - name: validator2
      bonded: 100000000stake
